title: Savvy Soft Life Mom  
description: Work-from-home tips without the guilt.  
theme: minima  # Default theme (simple and clean)  
email: savvysoftlifemom@gmail.com  
baseurl: ""  
url: "https://savvysoftlifemom.github.io"  
